#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Simple check for merge conflics
conflicts=`git diff --cached --name-only -G"<<<<<<<|=======|>>>>>>>"`
# If there is a conflict in the current file, omit it (because of the regex above)
conflicts=`echo $conflicts | sed -e 's/\.husky\/pre-commit//g'`

if [ -n "$conflicts" ]; then
	echo "🔥 Unresolved merge conflicts detected! Check the following files:"

	for conflict in $conflicts; do
		echo "\033[0;31m$conflict\033[0m"
	done;

	exit 1;
fi

exit 0

if [ -f ~/.signageos/npm.env ]; then
	# If the file containing env variables exists, load it
	. ~/.signageos/npm.env
fi

if [ -z "$NPM_AUTH_TOKEN" ]; then
	echo "Necessary env variables are not loaded and couldn't be obtained from the ~/.signageos/npm.env file."
	echo "The pre commit hook requires the NPM_REGISTRY_HOST, NPM_REGISTRY_URL and NPM_AUTH_TOKEN variables to be present."
fi

npm run lint:staged
